Added option for rounded rectangles
ej-shafran/sound-visualizer pull request #3
Opened 2024-02-10 11:49 UTC by theJsTsGuy

## Description
- Fixes: #2
- Moved the draw from stroke lines to filled `rect` and `roundRect`.
- Now `DrawContinuousOption` has `roundedRadius`, which will set the border radius of the bars.

**Test Code**:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Canvas</title>
  </head>
  <body>
    <canvas height="200" width="400" id="c"></canvas>
    <script type="module" src="./index.js"></script>
  </body>
</html>

```
```js
import { continuousVisualizer } from "./sound-visualizer/lib/index.mjs";

async function init() {
  const c = document.getElementById("c");
  const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
  continuousVisualizer(stream, c, { slices: 30, lineWidth: 5, roundedRadius: 50 }).start();
}
init();
```

**Preview:**

![Screenshot (6)](https://github.com/ej-shafran/sound-visualizer/assets/40920737/f8665afd-d1d7-4aef-a6d9-ce78a1f7875e)

2024-02-11 20:46 UTC, ej-shafran requested changes
Hey! Thanks for the pull request. Looks great. Please go over my two comments and fix them, and I'll merge this.

2024-02-11 20:46 UTC, ej-shafran commented on src/continuous/draw/impure.ts
> +  const w = widthFromOption(lineWidth, width);
Could you rename this variable to `rectWidth`?

2024-02-11 20:46 UTC, ej-shafran commented on src/continuous/draw/options.ts
> +  roundedRadius?: number;
Could you could call this option `barRadius`?

Also, I would use the word "rectangle" instead of "rect" in a documentation comment.

2024-02-13 08:20 UTC, ej-shafran approved these changes

2024-02-13 08:20 UTC, merged

2024-06-13 05:43 UTC, rangelojc commented
Was this PR ever released in NPM? I can't see the change. Typescript is still complaining with the barRadius option

2024-06-15 21:57 UTC, ej-shafran commented
> Was this PR ever released in NPM? I can't see the change. Typescript is still complaining with the barRadius option

You're right, I don't think I ever released this. Will publish to NPM later today.